### ISSUE TITLE
Error inflating class com.onegravity.rteditor.toolbar.RTToolbarImageButton

### ISSUE THREAD

**Issue by elnurvl** [1gravity/Android-RTEditor#109]
When I try to use RTEditor in a fragment of Navigation Drawer Activity the app crashes on the fragment.

Error on the Logcat:
`FATAL EXCEPTION: main
                                                              Process: com.elmxana.test, PID: 14301
                                                              android.view.InflateException: Binary XML file line #23: Binary XML file line #33: Error inflating class com.onegravity.rteditor.toolbar.RTToolbarImageButton
                                                              Caused by: android.view.InflateException: Binary XML file line #33: Error inflating class com.onegravity.rteditor.toolbar.RTToolbarImageButton
                                                              Caused by: java.lang.reflect.InvocationTargetException
                                                                  at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                  at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
                                                                  at android.view.LayoutInflater.createView(LayoutInflater.java:645)
                                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
                                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
                                                                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
                                                                  at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                                                                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
                                                                  at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                                                                  at android.view.LayoutInflater.parseInclude(LayoutInflater.java:994)
                                                                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:854)
                                                                  at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
                                                                  at com.elmxana.test.NewTopic.onCreateView(NewTopic.java:48)
                                                                  at android.support.v4.app.Fragment.performCreateView(Fragment.java:2239)
                                                                  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1332)
                                                                  at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1574)
                                                                  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1641)
                                                                  at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:794)
                                                                  at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2415)
                                                                  at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2200)
                                                                  at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2153)
                                                                  at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2063)
                                                                  at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:725)
                                                                  at android.os.Handler.handleCallback(Handler.java:751)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                  at android.os.Looper.loop(Looper.java:154)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
                                                               Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 13: TypedValue{t=0x2/d=0x7f01016c a=-1}
                                                                  at android.content.res.TypedArray.getDrawable(TypedArray.java:925)
                                                                  at android.view.View.<init>(View.java:4175)
                                                                  at android.widget.ImageView.<init>(ImageView.java:150)
                                                                  at android.widget.ImageButton.<init>(ImageButton.java:84)
                                                                  at android.widget.ImageButton.<init>(ImageButton.java:80)
                                                                  at com.onegravity.rteditor.toolbar.RTToolbarImageButton.<init>(RTToolbarImageButton.java:42)
                                                                  at com.onegravity.rteditor.toolbar.RTToolbarImageButton.<init>(RTToolbarImageButton.java:38)
                                                                  at java.lang.reflect.Constructor.newInstance0(Native Method) 
                                                                  at java.lang.reflect.Constructor.newInstance(Constructor.java:430) 
                                                                  at android.view.LayoutInflater.createView(LayoutInflater.java:645) 
                                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787) 
                                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727) 
                                                                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:858) 
                                                                  at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821) 
                                                                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:861) 
                                                                  at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821) 
                                                                  at android.view.LayoutInflater.parseInclude(LayoutInflater.java:994) 
                                                                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:854) 
                                                                  at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821) 
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:518) 
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:426) 
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:377) 
                                                                  at com.elmxana.test.NewTopic.onCreateView(NewTopic.java:48) 
                                                                  at android.support.v4.app.Fragment.performCreateView(Fragment.java:2239) 
                                                                  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1332) 
                                                                  at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1574) 
                                                                  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1641) 
                                                                  at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:794) 
                                                                  at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2415) 
                                                                  at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2200) 
                                                                  at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2153) 
                                                                  at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2063) 
                                                                  at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:725) 
                                                                  at android.os.Handler.handleCallback(Handler.java:751) 
                                                                  at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                  at android.os.Looper.loop(Looper.java:154) 
                                                                  at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866) 
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756) `

**Layout File:**
`<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
xmlns:tools="http://schemas.android.com/tools"
android:layout_width="match_parent"
android:layout_height="match_parent"
android:background="@color/white"
tools:context="com.elmxana.elmxana.Fragments.NewTopic">

<RelativeLayout
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <include
        android:id="@+id/rte_toolbar_container"
        layout="@layout/rte_toolbar" />

    <ScrollView
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:orientation="vertical">

            <com.onegravity.rteditor.RTEditText
                android:id="@+id/editor"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_weight="1"
                android:gravity="top"
                android:hint="Message"
                android:imeOptions="actionDone|flagNoEnterAction"
                android:inputType="textMultiLine|textAutoCorrect|textCapSentences" />
        </LinearLayout>
    </ScrollView>
</RelativeLayout>
</FrameLayout>`

Fragment is opened without an error when I remove `rte_toolbar`. So it is clearly due to the toolbar layout.

I wonder, why I get this error when I use Navigation Drawer activity and how can I get it worked just like on the Demo Project? I included the library remotely:

`dependencies {
    compile 'com.1gravity:android-rteditor:1.6.2'
}`

**Comment by 1gravity** [comment]
No problem ;-)

**Comment by dmkhedkar** [comment]
2022-04-11 15:50:10.044 7675-7675/com.example.testingapplication E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.testingapplication, PID: 7675
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.testingapplication/com.example.testingapplication.MainActivity}: android.view.InflateException: Binary XML file line #16 in com.example.testingapplication:layout/activity_main: Binary XML file line #33 in com.example.testingapplication:layout/rte_toolbar: Error inflating class com.onegravity.rteditor.toolbar.RTToolbarImageButton
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3654)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3806)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8167)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
     Caused by: android.view.InflateException: Binary XML file line #16 in com.example.testingapplication:layout/activity_main: Binary XML file line #33 in com.example.testingapplication:layout/rte_toolbar: Error inflating class com.onegravity.rteditor.toolbar.RTToolbarImageButton
     Caused by: android.view.InflateException: Binary XML file line #33 in com.example.testingapplication:layout/rte_toolbar: Error inflating class com.onegravity.rteditor.toolbar.RTToolbarImageButton
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:854)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1126)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
        at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1263)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1119)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:706)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:195)
        at com.example.testingapplication.MainActivity.onCreate(MainActivity.kt:11)
        at android.app.Activity.performCreate(Activity.java:7963)
        at android.app.Activity.performCreate(Activity.java:7952)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3629)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3806)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
2022-04-11 15:50:10.046 7675-7675/com.example.testingapplication E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:8167)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
     Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 13: TypedValue{t=0x2/d=0x7f040376 a=-1}
        at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:996)
        at android.content.res.TypedArray.getDrawable(TypedArray.java:980)
        at android.view.View.<init>(View.java:5692)
        at android.widget.ImageView.<init>(ImageView.java:193)
        at android.widget.ImageButton.<init>(ImageButton.java:96)
        at android.widget.ImageButton.<init>(ImageButton.java:92)
        at androidx.appcompat.widget.AppCompatImageButton.<init>(AppCompatImageButton.java:78)
        at com.onegravity.rteditor.toolbar.RTToolbarImageButton.<init>(RTToolbarImageButton.java:43)
        at com.onegravity.rteditor.toolbar.RTToolbarImageButton.<init>(RTToolbarImageButton.java:39)


Layout -->
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
  xmlns:app="http://schemas.android.com/apk/res-auto"
  xmlns:tools="http://schemas.android.com/tools"
  android:layout_width="match_parent"
  android:layout_height="match_parent"
  tools:context=".MainActivity">
  <com.onegravity.rteditor.RTEditText
    android:id="@+id/rtEditText"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:imeOptions="actionDone|flagNoEnterAction"
    android:inputType="textMultiLine|textAutoCorrect|textCapSentences"
    app:layout_constraintBottom_toBottomOf="parent"
    app:layout_constraintTop_toTopOf="parent" />
  <include android:id="@+id/rte_toolbar_container" layout="@layout/rte_toolbar" />

</androidx.constraintlayout.widget.ConstraintLayout>

version

dependencies {
    implementation 'com.1gravity:android-rteditor:1.7.6'
}

I have tried setting theme its not working. 
Am I missing anything?
Thanks in advance

**Comment by theoyuncu8** [comment]
https://github.com/1gravity/Android-RTEditor/issues/173

please review and help me
