### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException: The RTMediaFactory is null. Please make sure to register the editor at the RTManager before using it.

### ISSUE THREAD

**Issue by daerimin** [1gravity/Android-RTEditor#157]
This has started happening on Android 9 devices. Please advise.

Fatal Exception: java.lang.IllegalStateException: The RTMediaFactory is null. Please make sure to register the editor at the RTManager before using it.
       at com.onegravity.rteditor.RTEditText.assertRegistration(RTEditText.java:382)
       at com.onegravity.rteditor.RTEditText.getRichText(RTEditText.java:374)
       at com.onegravity.rteditor.RTEditText.getText(RTEditText.java:366)
       at com.onegravity.rteditor.RTEditText.onSaveInstanceState(RTEditText.java:551)

**Comment by starshipcoder** [comment]
I have same problem, I advice you to use [AztecEditor-Android](https://github.com/wordpress-mobile/AztecEditor-Android)

**Comment by donynuransyah** [comment]
just remove the `rtManager?.onDestroy(true)` solve the issue dunno why its messed up when i use it
