### ISSUE TITLE
[BUG] Caused by: android.view.InflateException: Binary XML file line #36 

### ISSUE THREAD

**Issue by theoyuncu8** [1gravity/Android-RTEditor#173]
I'm getting an error like here.. I tried all the steps but it didn't work.. I couldn't solve it. I also set the theme.. here's the thing

`        <activity
            android:name=".activity.PostAddActivity"
            android:exported="true"
            android:theme="@style/AppThemeACT"
            android:windowSoftInputMode="adjustResize|stateAlwaysHidden" />
            
          
        <provider
            android:name="androidx.core.content.FileProvider"
            tools:replace="android:authorities"
            android:authorities="${applicationId}.provider"
            android:exported="false" />
  
            `
            
            // Theme
            
            `    <style name="AppThemeACT" parent="Theme.AppCompat.Light">
        <item name="colorPrimary">@color/white</item>
        <item name="colorPrimaryDark">@color/white</item>
        <item name="colorAccent">@color/colorAccent</item>
        <item name="android:windowBackground">@color/white</item>
        <item name="bottomSheetDialogTheme">@style/AppBottomSheetDialogTheme</item>
        <item name="drawerArrowStyle">@style/DrawerArrowStyle</item>
        <item name="android:statusBarColor">@color/colorPalette4</item>
        <item name="hintTextColor">@color/greydefaultv2</item>
        <item name="android:textColorHint">@color/greydefaultv2</item>
        <item name="android:windowContentTransitions">true</item>
    </style>`

// BUG

` java.lang.RuntimeException: Unable to start activity ComponentInfo{com.myapp/com.myapp.activity.PostAddActivity}: android.view.InflateException: Binary XML file line #364 in com.myapp:layout/activity_post_add: Binary XML file line #36 in com.myapp:layout/rte_toolbar: Error inflating class com.onegravity.rteditor.toolbar.RTToolbarImageButton
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3846)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4022)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2336)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loop(Looper.java:246)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8653)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
                                                                                                    Caused by: android.view.InflateException: Binary XML file line #364 in com.myapp:layout/activity_post_add: Binary XML file line #36 in com.myapp:layout/rte_toolbar: Error inflating class com.onegravity.rteditor.toolbar.RTToolbarImageButton
                                                                                                    Caused by: android.view.InflateException: Binary XML file line #36 in com.myapp:layout/rte_toolbar: Error inflating class com.onegravity.rteditor.toolbar.RTToolbarImageButton
                                                                                                    Caused by: java.lang.reflect.InvocationTargetException`

// version
`  implementation 'com.1gravity:android-rteditor:1.8.0'`

/// Activity
`
@SuppressLint("SetTextI18n")
public class PostAddActivity extends AppCompatActivity {
    RTManager rtManager;

    @Override
    protected void onSaveInstanceState(Bundle outState) {
        super.onSaveInstanceState(outState);
        rtManager.onSaveInstanceState(outState);
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        // super.onCreate(savedInstanceState);
        setTheme(R.style.AppThemeACT);
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_post_add);
        setTitle(R.string.app_name);

        RTApi rtApi = new RTApi(this, new RTProxyImpl(this), new RTMediaFactoryImpl(this, true));
        rtManager = new RTManager(rtApi, savedInstanceState);

        ViewGroup toolbarContainer = findViewById(R.id.rte_toolbar_container);

        RTToolbar rtToolbar0 = findViewById(R.id.rte_toolbar);
        if (rtToolbar0 != null) {
            rtManager.registerToolbar(toolbarContainer, rtToolbar0);
        }

        RTEditText rtEditText = findViewById(R.id.rtEditText);
        rtManager.registerEditor(rtEditText, true);
        rtEditText.setRichTextEditing(true, "message");
    }
`

`
            <include android:id="@+id/rte_toolbar_container" layout="@layout/rte_toolbar" />

            <RelativeLayout
                android:id="@+id/post_layout"
                android:layout_width="match_parent"
                android:layout_height="@dimen/_120sdp"
                android:layout_marginTop="@dimen/_12sdp"
                android:layout_marginBottom="@dimen/_9sdp"
                android:background="@drawable/circularbordersolidv3_light"
                android:gravity="center"
                android:orientation="horizontal"
                tools:ignore="RtlSymmetry">

                <com.onegravity.rteditor.RTEditText
                    android:id="@+id/rtEditText"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    android:fontFamily="@font/poppins_regular"
                    android:gravity="start"
                    android:hint="start type.."
                    android:imeOptions="actionDone|flagNoEnterAction"
                    android:inputType="textMultiLine|textAutoCorrect|textCapSentences"
                    android:maxLength="2200"
                    android:minLines="6"
                    android:paddingStart="@dimen/_12sdp"
                    android:paddingTop="@dimen/_12sdp"
                    android:paddingEnd="@dimen/_12sdp"
                    android:paddingBottom="@dimen/_12sdp"
                    android:textColor="@color/black"
                    android:textColorHint="@color/darkgrey"
                    android:textSize="@dimen/_14ssp" />
            </RelativeLayout>
`

// end..

**Comment by Loki0724** [comment]
You need to use a theme based on either RTE_ThemeLight or RTE_ThemeDark
