### ISSUE TITLE
Rendering Problems

### ISSUE THREAD

**Issue by gukzilla** [1gravity/Android-RTEditor#32]
Please tell me how to solve this problem?

```
<LinearLayout
        android:id="@+id/rte_toolbar_container"
        android:orientation="vertical"
        android:layout_width="match_parent"
        android:layout_height="wrap_content" >

        <include layout="@layout/rte_toolbar_character" />
        <include layout="@layout/rte_toolbar_paragraph" />

    </LinearLayout>
```
Rendering Problems java.lang.NullPointerException   at com.onegravity.rteditor.fonts.FontManager.listFontFiles(FontManager.java:185)   at com.onegravity.rteditor.fonts.FontManager.listFontFiles(FontManager.java:178)   at com.onegravity.rteditor.fonts.FontManager.getAssetFonts(FontManager.java:158)   at com.onegravity.rteditor.fonts.FontManager.getFonts(FontManager.java:97)   at com.onegravity.rteditor.toolbar.HorizontalRTToolbar.getFontItems(HorizontalRTToolbar.java:213)   at com.onegravity.rteditor.toolbar.HorizontalRTToolbar.onFinishInflate(HorizontalRTToolbar.java:177)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:844)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:811)   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:838)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:811)   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)   at android.view.LayoutInflater_Delegate.parseInclude(LayoutInflater_Delegate.java:197)   at android.view.LayoutInflater.parseInclude(LayoutInflater.java:879)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:831)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:811)   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:838)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:811)   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)   at android.view.LayoutInflater.inflate(LayoutInflater.java:515)   at android.view.LayoutInflater.inflate(LayoutInflater.java:394)

At the time of launch activity.

E/AssetIndex: assets.index
java.io.FileNotFoundException: assets.index
at android.content.res.AssetManager.openAsset(Native Method)
at android.content.res.AssetManager.open(AssetManager.java:316)
at android.content.res.AssetManager.open(AssetManager.java:290)
at com.onegravity.rteditor.fonts.AssetIndex.getAssetIndex(AssetIndex.java:46)
at com.onegravity.rteditor.fonts.FontManager.getAssetFonts(FontManager.java:156)
at com.onegravity.rteditor.fonts.FontManager.getFonts(FontManager.java:97)
at com.onegravity.rteditor.toolbar.HorizontalRTToolbar.getFontItems(HorizontalRTToolbar.java:213)
at com.onegravity.rteditor.toolbar.HorizontalRTToolbar.onFinishInflate(HorizontalRTToolbar.java:177)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:763)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
at android.view.LayoutInflater.parseInclude(LayoutInflater.java:839)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:745)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:256)
at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109)
at com.cloudstechnologies.smartypro.activities.ActivityTaskEdit.onCreate(ActivityTaskEdit.java:73)
at android.app.Activity.performCreate(Activity.java:5231)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
at android.app.ActivityThread.access$800(ActivityThread.java:135)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5001)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
at dalvik.system.NativeStart.main(Native Method)

**Comment by gukzilla** [comment]
///
FATAL EXCEPTION: main
Process: com.cloudstechnologies.smartypro, PID: 29154
android.content.ActivityNotFoundException: Unable to find explicit activity class {com.cloudstechnologies.smartypro/com.onegravity.rteditor.media.choose.MediaChooserActivity}; have you declared this activity in your AndroidManifest.xml?
at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1628)
at android.app.Instrumentation.execStartActivity(Instrumentation.java:1424)
at android.app.Activity.startActivityForResult(Activity.java:3424)
at android.app.Activity.startActivityForResult(Activity.java:3385)
at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:784)
at com.onegravity.rteditor.api.RTProxyImpl.startActivityForResult(RTProxyImpl.java:50)
at com.onegravity.rteditor.api.RTApi.startActivityForResult(RTApi.java:121)
at com.onegravity.rteditor.RTManager.onPickCaptureImage(RTManager.java:504)
at com.onegravity.rteditor.RTManager.onCaptureImage(RTManager.java:492)
at com.onegravity.rteditor.toolbar.HorizontalRTToolbar.onClick(HorizontalRTToolbar.java:652)
at android.view.View.performClick(View.java:4438)
at android.view.View$PerformClick.run(View.java:18422)
at android.os.Handler.handleCallback(Handler.java:733)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5001)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
at dalvik.system.NativeStart.main(Native Method)
///

**Comment by 1gravity** [comment]
Three different problems --> please create three different issues. Putting everything in one makes it impossible to solve each problem separately and have it well documented.
