### ISSUE TITLE
Experiencing crash when on calling setContentView

### ISSUE THREAD

**Issue by kelvinwatson** [1gravity/Android-RTEditor#87]
I'm experiencing a crash when trying to import the editor into my project. This occurs at the line         ` setContentView(R.layout.activity_one_gravity_rte);`. I've set the theme before calling `setContentView` but am still experiencing the crash. My compile SDK version is 24.
    
-17 18:49:45.365 10288-10288/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.example.kelvwatson.boltdescriptionrichtexteditor, PID: 10288
                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.kelvwatson.boltdescriptionrichtexteditor/com.example.kelvwatson.boltdescriptionrichtexteditor.OneGravityRteActivity}: java.lang.IllegalStateException: This Activity already has an action bar supplied by the window decor. Do not request Window.FEATURE_SUPPORT_ACTION_BAR and set windowActionBar to false in your theme to use a Toolbar instead.
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
                                                    Caused by: java.lang.IllegalStateException: This Activity already has an action bar supplied by the window decor. Do not request Window.FEATURE_SUPPORT_ACTION_BAR and set windowActionBar to false in your theme to use a Toolbar instead.
                                                       at android.support.v7.app.AppCompatDelegateImplV9.setSupportActionBar(AppCompatDelegateImplV9.java:199)
                                                       at android.support.v7.app.AppCompatActivity.setSupportActionBar(AppCompatActivity.java:130)
                                                       at com.example.kelvwatson.boltdescriptionrichtexteditor.OneGravityRteActivity.onCreate(OneGravityRteActivity.java:27)
                                                       at android.app.Activity.performCreate(Activity.java:6664)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707) 
                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:154) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by kelvinwatson** [comment]
Sorry, figured this out. I had to remove the default toolbar.

**Comment by VAIMORSS** [comment]
Hello there 
I am new to fragment can you describe? How you solved the problem?
